In [1]:
import pandas as pd

In [2]:
data=pd.read_html('https://en.wikipedia.org/wiki/Weather_Report')

In [5]:
len(data)

7

In [6]:
data[0]

Weather Report  \
0  Weather Report live June 11, 1981   
1             Background information   
2                             Origin   
3                             Genres   
4                       Years active   
5                             Labels   
6                                NaN   
7                       Past members   

                                    Weather Report.1  
0                  Weather Report live June 11, 1981  
1                             Background information  
2                      New York City, New York, U.S.  
3     Jazz fusion, world music, jazz-funk, free jazz  
4                                          1970–1986  
5                                      Columbia, ARC  
6                                                NaN  
7  Joe ZawinulWayne ShorterJaco PastoriusMiroslav...

In [7]:
import numpy as np

In [15]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [16]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [17]:
a = np.array([1, 2, 3, 4, 5], ndmin = 2)
a

array([[1, 2, 3, 4, 5]])

In [27]:
a = np.array([1 + 3j, 2, 3], dtype = complex)
a

array([1.+3.j, 2.+0.j, 3.+0.j])

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [29]:
a.ndim

2

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a.shape = (3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3, 2)
print('a = ' + str(a))
print('b = ' + str(b))

a = [[1 2 3]
 [4 5 6]]
b = [[1 2]
 [3 4]
 [5 6]]


In [45]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [47]:
x = np.arange(10, 20, 2)
print(x)

[10 12 14 16 18]


In [49]:
b = a.reshape(2, 4, 3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [58]:
matrix1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.matrix([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [61]:
#2-D Matrix Transpose

TransRes = matrix1.transpose()
print('Original: ' + str(matrix1))
print('Transpose: ' + str(TransRes))

Original: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [53]:
#2-D Matrix Multiplication

MultRes = np.dot(matrix1, matrix2)
MultRes

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [67]:
#Change list to numpy array

MOneShape = matrix1.shape
arr1 = np.array(MOneShape)

print ("List: ", MOneShape)
print ("Array: ", arr1)

List:  (3, 3)
Array:  [3 3]


In [72]:
#bincount

#arr = np.array([[1, 2, 1], [3, 5, 7], [5, 3, 2]])
arr = np.array([1, 2, 1, 5, 3, 2, 5, 1, 5])

np.bincount(arr)

array([0, 3, 2, 1, 0, 3], dtype=int64)

In [ ]:
#flaten
#ravel